### ISSUE TITLE
新增项目：i乐学助手

### ISSUE THREAD

**Issue by YDX-2147483647** [YDX-2147483647/best-of-bits#158]
### 名称

i乐学助手

### URL

https://github.com/BobH233/LexueSwiftUI

### 类别

👩‍🏫教学运行与考务

### 补充信息

App Store：https://apps.apple.com/cn/app/i%E4%B9%90%E5%AD%A6%E5%8A%A9%E6%89%8B/id6468846337

#### ~~统计数据~~

~~是否有办法记录 App Store 上的下载量、评分？~~

有第二个上架 App Store 的项目再说吧。#142 bit-genshin 涉及 userstyles.world，也还没有数据。

#### 描述

仓库的项目描述不太清楚；以下修改自 App Store 的描述。（→ https://github.com/BobH233/LexueSwiftUI/issues/1 ）

> 为北京理工大学“乐学”提供服务的iOS端手机应用，具有“临近作业期限提醒”“小组件显示最近日程”“聚合全校消息通知”等增强功能，为北京理工大学的同学提供更方便的使用体验。

#### 分类

以下几类都沾边儿。

- 👩‍🏫教学运行与考务
- 📥汇总或重定向信息
- 📅管理时空流形

**Comment by BobH233** [comment]
> 是否有办法记录 App Store 上的下载量、评分？

我可以将你的Apple Developer账户设置为i乐学助手项目的“app管理”负责人，这样你就可以通过登录Apple Developer官网查看app的下载销售情况。不过这个过程不会自动化的，苹果也许会限制爬虫自动爬取。
