### ISSUE TITLE
点击README Contents里的链接不能跳转到目标位置

### ISSUE THREAD

**Issue by Devil-SX** [YDX-2147483647/best-of-bits#40]
点击“网络”、“模板”...等不能跳转到目标位置

![image](https://github.com/YDX-2147483647/best-of-bits/assets/77198466/4da4610e-dfb8-4341-b871-af69b5af24ef)

**Comment by YDX-2147483647** [comment]
Duplicate of #19 

已经解决了，下周更新会生效。要是你着急，我也可以手动更新一下。

**Comment by YDX-2147483647** [comment]
> 话说非管理员不能给issue添加label吗

[GitHub 文档]: “对存储库具有写入访问权限的任何人都可以创建标签。”
