### ISSUE TITLE
新增项目：北京理工大学集成电路设计实践1HDL代码

### ISSUE THREAD

**Issue by Devil-SX** [YDX-2147483647/best-of-bits#41]
### 名称

北京理工大学集成电路设计实践1

### GitHub URL

https://github.com/Devil-SX/integrated_circuit_practice

### 类别

📚学习资料

**Comment by YDX-2147483647** [comment]
这和现有学习资料不太一样，不存在长期维护的可能性，将来只能考古。

- 自己结课后不会再做当时的实验。
- 其他人不会（至少不应当）在你的基础上继续工作。

要不新建一类？

**Comment by Devil-SX** [comment]
> 

我觉得一层分类不太够了（）

**Comment by Devil-SX** [comment]
> 这和现有学习资料不太一样，它不存在长期维护的可能性，将来恐怕只能考古。
> 
> * 自己结课后不会再做当时的实验。
> * 其他人不会（至少不应当）在你的基础上继续工作。
> 
> 要不新建一类？

一层分类可能不太够（）

**Comment by YDX-2147483647** [comment]
我试了一下`group`，感觉不太适合。

- 整个组必须有个主页。
- 排序时组作为整体来排，组内的项目不再单独排。

要不直接加入学习资料？

**Comment by YDX-2147483647** [comment]
抱歉我不小心错过了本周更新……昨天考试，忘了审了。
