### ISSUE TITLE
新增项目：BIT-Zongce

### ISSUE THREAD

**Issue by Devil-SX** [YDX-2147483647/best-of-bits#97]
### 名称

BIT-Zongce

### URL

https://github.com/Devil-SX/BIT-Zongce

### 类别

📬学生事务

**Comment by YDX-2147483647** [comment]
能否选一下类别？请尽量从 https://github.com/YDX-2147483647/best-of-bits#contents 里选。

**Comment by Devil-SX** [comment]
> 能否选一下类别？请尽量从 https://github.com/YDX-2147483647/best-of-bits#contents 里选。

似乎选不出...

**Comment by YDX-2147483647** [comment]
类别名你有什么想法吗？

**Comment by Devil-SX** [comment]
感觉现在几个类是这么个逻辑

- 事务类
  - 北理生活
    - 认证校园网
    - 学校网站与网络（似乎这个放在“北理生活”里也不太恰当）
    - 管理时空流行
  - 教务信息
    - 汇总或重定向信息
    - 教学运行与考务
  - 办公提交
    - 模板
    - 格式工具 <- 放这    
  - 校园组织
    - 存在一定结构的人的集合 
- 学习类
  - 学习资料
  - 实验/实践
  
  大概想的分了一下类

**Comment by YDX-2147483647** [comment]
这是各类的项目数量。

- 89 事务类

  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

  - 39 北理生活 ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

    - 24 认证校园网 ■■■■■■■■■■■■■■■■■■■■■■■■

    - 6 学校网站与网络 ■■■■■■

    - 9 管理时空流形 ■■■■■■■■■

  - 31 教务信息 ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

    - 8 汇总或重定向信息 ■■■■■■■■

    - 23 教学运行与考务 ■■■■■■■■■■■■■■■■■■■■■■■

  - 12 办公提交 ■■■■■■■■■■■■

    - 12 模板

  - 7 校园组织 ■■■■■■■

    - 7 存在一定结构的人的集合 

- 26 学习类

  ■■■■■■■■■■■■■■■■■■■■■■■■■■

  - 18 学习资料 ■■■■■■■■■■■■■■■■■■

  - 8 实验/实践 ■■■■■■■■

- 17 其它

  ■■■■■■■■■■■■■■■■■

  - 6 First BIT for Mankind ■■■■■■

  - 11 杂项 ■■■■■■■■■■■

**Comment by Devil-SX** [comment]
> 由使用者命名，叫“学生工作”“学生事务”或“办公”怎么样？

善
